Import numpy

In [3]:
import numpy as np

Numpy - to create and deal with Arrays

In [10]:
a = np.array([1,2,3])
print(a)
print(type(a))
print(a.ndim)
print(a.shape)

[1 2 3]
<class 'numpy.ndarray'>
1
(3,)


In [45]:
b = np.array([[1,2,3] ,[4,5,6]])
print(b)
print(type(b))
print(b.ndim)
print(b.shape)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
2
(2, 3)


In [46]:
c = np.array([[1,2,3] ,[4,5,6],[7,8,9]])
print(c)
print(type(c))
print(c.ndim)
print(c.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
2
(3, 3)


great!